### PR TITLE
Fixed and improved cell meta to respect adding and deleting

### PR DESCRIPTION
**Pull request by rozwell**
There are a few main changes here:
1. Improved `setMeta()` to support setting meta information for entire cell
2. Improved `setMeta()` to call `updateTableReferences()` - in case something in a table relies on meta information (we use `updateTable()` option to tune cells based on their meta)
3. **Adding/removing columns and rows now adjust meta information accordingly(!)**
4. All console output commands start with "JEXCEL: " - to be clear and consistent

What is missing in this pull request:
1. Support for meta in `undo()` & `redo()`

What is missing in general:
2. Cell merging is supported by `undo()` but not by `redo()`

I have tried to fix `undo()` & `redo()` but it seems to require more time than I can spend ATM.
Moreover, these methods use opposite function for every type of event to revert changes which seems to be more optimal but also complicate things significantly and introduce plenty of bugs.
Is performance a reason to not use entire snapshots of the table which would pretty much solve them all?

### CODE REVIEW

**Comment by pphod** [comment]
Thanks for that. I going to think about that. I was thinking to use a meta tag property like in v2. 

data-k=v so if you move the colums away this does not represent a problem... if we keep like that, we would have serious problems to control, sortingColumns, moveColumns, moveRows, insert & deletes, undo, history, etc.

It will create a huge overhead. If use meta tag we easily overcome all of this.

**Review by pphod — COMMENTED** [review]
I am not sure if you can remove updateTableReferences. More detailed tests will be required.

**Comment by rozwell** [comment]
I should create different branch with these changes cause this one is used in a project :)

This can be easily fixed, but first a little background of why I removed it ATM:
In current implementation `setMerge()` has to be called for every cell merge because of NODEs stored in `mergeCells`.
Native undo&redo aren't reliable at this point and I hardly rely on meta data, so I created my own implementation of history which saves whole snapshot of the configuration (data/meta/mergeCells/etc.) - it works very stable.
When I apply the snapshot, it can contain multiple merged cells and calling `updateTableReferences()` every time is far from optimal. That's why I call it manually when everything else is done.

I'll re-add `updateTableReferences()` with `setMerge()` accepting multiple merged columns at once.

I'm missing method to update whole configuration from these kind of snapshots on the fly, but this really required getting rid of NODEs in config. This would be far more optimal to stop updating references before whole configuration is applied.

Also, I ran into some issues with merged columns due to the fact hidden/merged columns are referenced to the primary column node and since I use `updateTable()` to adjust each cell `innerHtml`, applying data from meta to those hidden/merged columns was changing my primary cell.

I eventually realized that and added a check if nodes `data-x` & `data-y` are matching cell actual `x` & `y`.

**Comment by rozwell** [comment]
> I am not sure if you can remove updateTableReferences. More detailed tests will be required.

I've removed that commit here, using different branch for the project.
I guess I should create different branches for different issues - let me know if that's needed ;)

**Comment by pphod** [comment]
I am going to review this one to use the meta tag property. So, this will cause lot of conflicts.

**Comment by rozwell** [comment]
Sure, no problem.
I like your idea to store data directly in cells, this way you won't have all the overhead when deleting, moving, adding, etc.
If I'll have some extra time, I'll try to do it.

**Pull request closed without merging**
