### PR TITLE
Use only text for title on Cellheader

### PR DESCRIPTION
**Pull request by GBonnaire**
If you use title with HTML, the title show html tag not interpreted.

For this issues, i have changed on obj.createCellHeader

```
if (obj.options.columns[colNumber].title) {
      obj.headers[colNumber].setAttribute('title', obj.options.columns[colNumber].title);
}
```

to

```
if (obj.options.columns[colNumber].title) {
        obj.headers[colNumber].setAttribute('title', obj.headers[colNumber].textContent);
}
```

### CODE REVIEW

**Comment by pphod** [comment]
This:
obj.headers[colNumber].setAttribute('title', obj.options.columns[colNumber].title);

Should add a string to the property title in the HTML. Not sure if I understood this correctly.

**Comment by GBonnaire** [comment]
Hi Paul,

In title, I have a html (<br>), and on hover mouse, <br> is show in title (tips). For this bug, I propose delete tag HTML for title 😊 

Example :
In option set : My<br>title
In header show : My
title
In tips show : My<br>title

With my PR
In option set : My<br>title
In header show : My
title
In tips show : My title

**Comment by pphod** [comment]
Ok, I will merge that. Sorry, did not understand. I am working to launch CE v4 soon.

**Comment by GBonnaire** [comment]
Yeah good job for v4 😁 👍

**Comment by pphod** [comment]
It has been included, sorry about the big delay.

**Pull request closed without merging**
