### PR TITLE
Fix shift preventing cell editor invocation

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
See #433. Credit to @TheNeverK for [the fix](https://github.com/paulhodel/jexcel/issues/433#issuecomment-510369856)

New PR based on #440. Turns out that removing a wrapping if-statement makes ugly diffs and merging upstream changes a pain.

### CODE REVIEW

**Comment by AnaOrtega1** [comment]
Is this going to make it in the next release? The message above says there were conflicts. I need this to be able to enter proper names in the cells easily. Thank you!!!

**Comment by seth-shaw-unlv** [comment]
I have no idea, @AnaOrtega1. I haven't heard anything from the maintainer. 

I resolved conflicts earlier, but additional changes were merged since then and now we have conflicts again. I'm not inclined to keep resolving conflicts if the PR continues to be ignored. ☹️

**Comment by pphod** [comment]
Hi Seth, I am happy to include that. The problem there were so many changes it makes this job very hard.

**Comment by seth-shaw-unlv** [comment]
In that case, I'll see if I can resolve the conflict tomorrow. I probably won't get to it today due to meetings.

**Comment by seth-shaw-unlv** [comment]
Turns out I was able to update the PR today after all. Unfortunately, pulling upstream into this branch didn't work well. Instead I made a new branch and PR. See #597.

**Pull request closed without merging**
