### PR TITLE
Fix for issue #1308

### PR DESCRIPTION
**Pull request by GBonnaire**
Fix for issue explain in #1308

When click right on header of column (when no click before in jexcel)

### CODE REVIEW

**Review by hodeware — APPROVED** [review]

**Comment by hodeware** [comment]
That has been merged...

**Comment by hodeware** [comment]
Thanks

**Comment by lhassis** [comment]
Is this fix going to be released?

**Review by hodeware — COMMENTED** [review]
That has been merged manually.

**Comment by hodeware** [comment]
That is already in the repository. It has been merged manually. Thanks

**Comment by lhassis** [comment]
Thank you @hodeware ! I was running version 4.6 and now upgraded to version 4.7!

**Pull request closed without merging**
