### PR TITLE
Generalise AJAX calls to allow for POST requests

### PR DESCRIPTION
**Pull request by darkxst**
Add settings that allow for setting a post request and post data. The underlying jsuite.ajax() already has support for this.

I am working with large datasets and server side filtering with fairly complex filters that are a bit nicer to handle with POST requests.

I haven't touched the autocomplete ajax call, as it seems to make less sense there, however similar could be done through the column settings.

### CODE REVIEW

**Comment by pphod** [comment]
We are still considering your PR. If we think about RESTful requests, we don't feel we are doing the right thing. I am going to leave this open for a little more time to get other users opinion about that.

**Comment by krosoftware** [comment]
I also have large dataset and autocomplete (dropdown) is not best option, because most of data does not exists in the database, so more than 75% will be new entries but I still want to get 25% of existing data. Best option will be some event so when I type, it should post some ajax to get data from server.

**Comment by jabis** [comment]
There might be a lot more query string data totally, unrelated to the jexcel, which on certain browsers just snuff the request, thus POST request is indeed needed to overcome this

**Comment by FranciscoMiralha** [comment]
An API first approach would definitely be fantastic, especially for large data sets.

BTW: Great great job so far!   (:

**Review by pphod — APPROVED** [review]

**Comment by pphod** [comment]
Those have been included.

        // Loading default configuration
        var defaults = {
            // External data
            url:null,
            // Ajax options
            method: 'GET',
            requestVariables: null,

**Pull request closed without merging**
