### PR TITLE
Drag row handle based on control width

### PR DESCRIPTION
**Pull request by mubarakzyanov**
Drag row handle based on control width

### CODE REVIEW

**Comment by Taapo** [comment]
Hi Paul, we wanted to have a bit more control about the handle size, so we added this to your code. Since we'd like to keep the library up to date without patching everytime - would you consider merging this change with your code?

**Comment by pphod** [comment]
I am happy to merge major of the contributions. But, the point is that this width you are getting is defined by the CSS, so you know the value, and it should be the same, always.

```
.jexcel > tbody.draggable > tr > td:first-child::after
{
    content:'\00a0';
    width:3px;
    height:100%;
    position:absolute;
    top:0px;
    right:0px;
    cursor:move;
}
```

In the original code, we defined as 6px to give a little flexibility in the mouse over. So, I am not sure of the benefits of that:

var rowDragControlWidth = parseInt(window.getComputedStyle(e.target, ':after').width);

It seems pointless, or I am losing something here?

Regards,

**Comment by mubarakzyanov** [comment]
Hi, Paul thanks for reply.
We are stuck when trying to drag rows because 6px is very small to use.
So pull request gives ability to control on drag by :after width set by css.
Maybe dynamic calculation is overhead and 6px should be controlled by configuration?

**Comment by pphod** [comment]
What is the value you think is ideal?

**Comment by mubarakzyanov** [comment]
I think this value need to be calculated from :after pseudoelement with paddings.
For ability to control :after pseudoelement by css - for example placing icon.

image

**Comment by Taapo** [comment]
Your library is prefect for a small Airtable clone, but it was missing some functionality, especially the sorting possibility (in an easy way). We think this would enhance your library even more. Would you consider implementing the changes we propose? Then we can submit a new pull request.

**Comment by pphod** [comment]
You can do sorting. Double click in the header, or via contextMenu or programatically.

myTable.orderBy(columnNumber, direction);

**Comment by Taapo** [comment]
Ok, but visually it is not very clear to the user. The solution we propose is adding a drag and drop handle through the use of an icon. The change in code would make it easier for anyone to add a handle of his/her choice - or don't use it at all.

**Comment by pphod** [comment]
Sorry, are you talking about sorting or dragging?

**Comment by pphod** [comment]
I am happy to consider all suggestions. Could you kindly add your suggestions in a separated issue?

**Comment by Taapo** [comment]
Sorry, my fault - I meant dragging. I can show you the functionality, but rather do it in a PM. I'll send you a link in a minute.

**Comment by pphod** [comment]
Ok, understood. Yes, I am considering to add that. It will change things slighter and will be an option, so anyone can enable or not that feature.

**Comment by Taapo** [comment]
Cool, thanks. I just sent you an email with the example which we created. However it's implemented, we'd welcome the option quite a lot :)

**Comment by pphod** [comment]
Yes, I am going to add something nice as this one. Just need to think about a problem for large tables with long numbers.

**Comment by vik17ag** [comment]
Hello, 
How can we look at this sorting feature in consideration? Is there any demo / fiddle /codesandbox? Or when will it be integrated with Jexcel library?

**Comment by pphod** [comment]
Vik17ag. I am sorry, but I am not sure. What sorting feature do you mean?

**Pull request closed without merging**
