### PR TITLE
Print function

### PR DESCRIPTION
**Pull request by GBonnaire**
Print function and add shortcut Ctrl+P for launch print.

I used options in function print as :  {title: {string}, header: {bool}, index: {bool}, autoprint: {bool}, style: {string}, stylesheet: {url}

Title of page and on top of page
header : show header column
index : show index column
autoprint : start auto print after load print page
style : specific style
stylesheet : url of specific stylesheet

TODO next update : print lot of column on multipage, actually overflow is hidden on chrome, safari..

Test on safari : OK (not OK with lot of column)
Test on chrome : OK (not OK with lot of column)
Test on firefox : OK
Test with nestedHeader : OK
Test with style on cell writed by editing : OK
Test with filtering table : OK (show all row)

In your code, there is 2 shortcut CTRL+S, i have replace 1 to CTRL+P 😉

### CODE REVIEW

**Comment by GBonnaire** [comment]
I see error with MergedCell, i search apply a correction on my code..

**Comment by pphod** [comment]
did you consider lazyLoading and pagination?

**Comment by GBonnaire** [comment]
yes, if i understand, all data is in obj.options.data, and i loop on obj.options.data, if cell is defined on record, get info on record else run executeFormula with data in obj.options.data. is correct ?

**Comment by GBonnaire** [comment]
i have updated my code with MergedCell for print and test for executeFormula (not run if "=" not exist)

**Pull request closed without merging**
