### PR TITLE
csvHeaders, domainClassess

### PR DESCRIPTION
**Pull request by dexterouschen**

### CODE REVIEW

**Comment by pphod** [comment]
could you send more information about your new proposal features?

**Comment by dexterouschen** [comment]
Sure thing. For the csvHeaders option, it is currently used as a boolean flag for using headers in CSV export but the headers can only be the colHeaders, it's fine for normal use yet I encountered this situation when I needed to use abbreviations in display for simplicity (otherwise the table got too wide) in UI but for the CSV I wanted the full names. Instead of creating another option, I rode on the csvHeaders option to make it accept an array, so I could use alternative header in CSV. Since array != true, this won't interfere with existing functionalities.

For the domainClasses, now if user clicks outside of jexcel's domain, the selection gets reset. It's fine for default, yet for custom editors, I'm using external modals, when user click inside of the modal, since it's technically out, the selection gets reset, user can lose track of the cell easily they just edited in a large table. So in order to include custom editors inside jexcel's domain, I added domainClasses option to extend the default .jexcel class. So any operation within any domain specified won't trigger the reset.

I'm also thinking about a noExport column option for selective CSV exporting, thoughts?

**Comment by pphod** [comment]
if your external modal contain the class jexcel this is not necessary.

**Comment by dexterouschen** [comment]
@paulhodel I've been working with 2.1.0 recently and this seems to be an issue still. Sure I can add .jexcel to external modal, but as long as I use the default jexcel stylesheet, there will be tons of styles that are designed for jexcel but not really for the external modal, which results in a broken page. I can confirm that adding .jexcel to Bootstrap modals would not work. It should really just be a separate class that is not referred anywhere in the jexcel code besides that one line determining if the modal is within the domain.

**Pull request closed without merging**
